package poly.util;

public enum PageType {
	AD_USER_PAGE, AD_REPORT_PAGE, AD_VIDEO_PAGE, SITE_HOME_PAGE, SITE_LOGIN_PAGE, SITE_REGIS_PAGE,
	SITE_CHANGE_PASSWORD_PAGE, SITE_EDIT_PROFILE_PAGE, SITE_FORGOT_PASSWORD_PAGE, SITE_FAVORITE_PAGE,
	SITE_VIDEO_DETAIL_PAGE, SITE_SHARE_PAGE
}
